version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - db
